backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "thoughts"
    label: "Pensées"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Pensée FR", name: "fr", widget: "text"}
      - {label: "Thought EN", name: "en", widget: "text"}
